### ISSUE TITLE
Compilation error in Visual Studio 2013

### ISSUE THREAD

**Issue by DiaLife** [SuperV1234/Tutorials#4]
\DiveIntoC++11\1_Arkanoid\p9.cpp

error C2144 and error C4430 on line 6:

constexpr int windowWidth{ 800 }, windowHeight{ 600 };

**Comment by SuperV1234** [comment]
Unfortunately `constexpr` isn't supported by Visual Studio 2013, sorry!
I suggest updating to the newest Visual Studio or using MinGW for windows modern C++ development.
