### ISSUE TITLE
RenderWindow window{ { (unsigned int)windowWidth, (unsigned int)windowHeight }, "Arkanoid - 9" };

### ISSUE THREAD

**Issue by ScottHuangZL** [SuperV1234/Tutorials#6]
VS2017:

RenderWindow window{ { windowWidth, windowHeight }, "Arkanoid - 9" };
**need change to:**
RenderWindow window{ { (unsigned int)windowWidth, (unsigned int)windowHeight }, "Arkanoid - 9" };

Due to the const int cannot need convert to unsigned int under VS2017 or VS2015 enviroment.

**Comment by SuperV1234** [comment]
This is a MSVC bug. 
Context & information: http://stackoverflow.com/questions/43076106

I'll report it if it's not already on the tracker.
